### ISSUE TITLE
Error:(79, 0) No such property: sonatypeRepo for class: org.gradle.api.publication.maven.internal.deployer.DefaultGroovyMavenDeployer

### ISSUE THREAD

**Issue by farmazon3000** [mrmans0n/smart-location-lib#101]
I've just cloned the repo, imported to Android Studio and gradle sync failed with:
```
Error:(79, 0) No such property: sonatypeRepo for class: org.gradle.api.publication.maven.internal.deployer.DefaultGroovyMavenDeployer
<a href="openFile:/home/fr/githubzz/smart-location-lib/library/build.gradle">Open File</a>
```

**Comment by mrmans0n** [comment]
copy gradle.properties.example to gradle.properties

**Comment by farmazon3000** [comment]
I don't understand, what is "gradle.properties.example" and what is "gradle.properties"?

**Comment by jendakol** [comment]
I believe mrmans0n meant file "gradle.properties.example" in root of this repository...

**Comment by mrmans0n** [comment]
Rename this file https://github.com/mrmans0n/smart-location-lib/blob/master/gradle.properties.example to "gradle.properties"

**Comment by farmazon3000** [comment]
Aren't issues created for the purpose to be fixed by library owner? No on user/developer side?

**Comment by mrmans0n** [comment]
Ehm... this is not an issue. I have a gradle.properties in my local machine with my sonatype passwords, which I don't want to share with other people. You should just copy the example file, as it is ignored in the .gitignore file. 

If copying a file to have other name is too hard or much of an inconvenience...

Anyway, you can use the dependency like everybody else and you wouldn't need to clone the repo in your local machine :smile:

**Comment by farmazon3000** [comment]
"If copying a file to have other name is too hard or much of an inconvenience..."
Currently you have 46 watchers and 399 forks, it means that some number of people will have to do it every git pull.

**Comment by awayo** [comment]
Don't, you only must to change that file once, or add the sonaType properties to your gradle.properties file.

**Comment by mrmans0n** [comment]
It is ignored in the .gitignore file, if you copy it once you don't have to do it again.

**Comment by farmazon3000** [comment]
Thanks I'll do so.

But then why this is repo anyway? Maybe I don't understand something about maven/gradle/library distribution but I don't have such problems with other libraries.
