### ISSUE TITLE
BlockingConnect must not be called on the UI thread

### ISSUE THREAD

**Issue by DobrinAlexandru** [mrmans0n/smart-location-lib#103]
I've updated the library from 3.0.1 to 3.2.0 and this error occurs when i start location query 

 W/System.err﹕ java.lang.IllegalStateException: blockingConnect must not be called on the UI thread
11-09 15:53:44.619    4440-4440/com.intersect.app W/System.err﹕ at com.google.android.gms.common.internal.zzv.zza(Unknown Source)
11-09 15:53:44.619    4440-4440/com.intersect.app W/System.err﹕ at com.google.android.gms.common.api.zzg.blockingConnect(Unknown Source)
11-09 15:53:44.619    4440-4440/com.intersect.app W/System.err﹕ at io.nlopez.smartlocation.location.providers.LocationGooglePlayServicesProvider.start(LocationGooglePlayServicesProvider.java:115)
11-09 15:53:44.619    4440-4440/com.intersect.app W/System.err﹕ at io.nlopez.smartlocation.location.providers.LocationGooglePlayServicesWithFallbackProvider.start(LocationGooglePlayServicesWithFallbackProvider.java:54)
11-09 15:53:44.619    4440-4440/com.intersect.app W/System.err﹕ at io.nlopez.smartlocation.SmartLocation$LocationControl.start(SmartLocation.java:210)

**Comment by masoudfcr** [comment]
Same thing happens with me!!

**Comment by masoudfcr** [comment]
found the solution...
update google play service
