### ISSUE TITLE
Android 6.0 Crash(Genymotion)

### ISSUE THREAD

**Issue by rohanmahale** [mrmans0n/smart-location-lib#107]
I am using the location lib and it has been working well on versions  5.x >. 
The following works perfectly fine on Genymotion's emulator below 6.0. I call this in OnCreate() of my Application sub-class.

        void setupLocationListener() {
        SmartLocation.with(getApplicationContext()).location().start(new OnLocationUpdatedListener() {
            @Override
            public void onLocationUpdated(Location location) {
                latitude = location.getLatitude();
                longitude = location.getLongitude();
            }
        });
    }

However, on a 6.0 emulator, it crashes. Is this a bug or am I going wrong some where?

**Comment by mtrakal** [comment]
On Android 6 you must request user for location permission (in default all "dangerous" permissions are rejected).

Great description about new permission system is here: http://inthecheesefactory.com/blog/things-you-need-to-know-about-android-m-permission-developer-edition/en

**Comment by rohanmahale** [comment]
I added the required permissions and then tried. The above code causes the app to crash. If I comment it out, it works fine!

**Comment by rohanmahale** [comment]
Is this happening because Genymotion(default) does not have google play services?  I installed the app on a Android M emulator(with google APIs) that I created in Android Studio and it did not crash.
