### ISSUE TITLE
Not getting location on Android 6.0+

### ISSUE THREAD

**Issue by witalobenicio** [mrmans0n/smart-location-lib#110]
In all marshmallow devices im not able to get the onLocationUpdated method called.

SmartLocation.with(context).location()
				.oneFix()
				.start(new OnLocationUpdatedListener() {
					@Override
					public void onLocationUpdated(Location location) {
						localizacao = location;

						for (ServiceGPSListener s : listeners){
							s.onLocationChanged(location);
						}
					}
				});

**Comment by arashifunsho** [comment]
Yo bro.... How did you solve this issue?

**Comment by hasnain-ahmad** [comment]
any solution?
