### ISSUE TITLE
Library Error

### ISSUE THREAD

**Issue by petrorington** [mrmans0n/smart-location-lib#115]
I had the error in building library of the project. 

"Error:(79, 0) No such property: sonatypeRepo for class: org.gradle.api.publication.maven.internal.deployer.DefaultGroovyMavenDeployer
<a href="openFile:F:\android_work\Samples\GetCurrentLocation\smart-location-lib-master\library\build.gradle">Open File</a>"

**Comment by mrmans0n** [comment]
Rename the gradle.properties.example file to gradle.properties

**Comment by petrorington** [comment]
Well...

**Comment by petrorington** [comment]
it works as well.
Hello,  i want to get the address from the latitude and longitude.
in the app, i got the latitude and longitude only.
