### ISSUE TITLE
Not working in Genymotion

### ISSUE THREAD

**Issue by radimvaculik** [mrmans0n/smart-location-lib#12]
Smartlocation library not working in Genymotion emulator. After sets GPS coords in emulator, smart-location-lib doesn't recognize location. Google Maps works in Genymotion correctly. Is there change to fix that? Thanks!

**Comment by PoCk3T** [comment]
Hello guys,

First of all, congrats for the greab lib, it's so easy to implement and working like a charm on my real devices.

For Genymotion, that's another story though... I have read all the thread here but still get no location in GenyMotion, even with Geny GPS enabled + Location ON in Android settings.

Here is how I start SmartLocation from my MainActivity :

SmartLocation.with(this).location()
                .provider(new LocationGooglePlayServicesWithFallbackProvider(this))
                .start(new OnLocationUpdatedListener() { .... });

But still, in one fragment of this activity, SmartLocation.with(context).location().getLastLocation() would stay NULL  :(

Any idea ? :)
Lucas

**Comment by ariefbayu** [comment]
Hi all,

I created gist that work well on genymotion and other non google play service devices:

https://gist.github.com/ariefbayu/12c8bef435dd5b14e94c

The trick is in this:

    .config(LocationParams.NAVIGATION)
    .provider(new LocationGooglePlayServicesWithFallbackProvider(getApplicationContext()))
