### ISSUE TITLE
How to check if location is on or not? supported with this lib or not?

### ISSUE THREAD

**Issue by amankumarjain** [mrmans0n/smart-location-lib#121]

**Comment by VaibhavSavla** [comment]
From the sample app

    provider = new LocationGooglePlayServicesProvider();
    provider.setCheckLocationSettings(true);
    SmartLocation smartLocation = new SmartLocation.Builder(this).logging(true).build();
    smartLocation.location(provider).start(this);

**Comment by dimparf** [comment]
But its not working on sample app.

**Comment by dimparf** [comment]
Sorry, I hurried to answer. When I turned on logging, I saw the need to do this to work. :)

**Comment by shukerullah** [comment]
provider.setCheckLocationSettings(true) is not working, im using sample.

**Comment by dimparf** [comment]
+1

**Comment by droidster** [comment]
@dimparf If you think your issue is solved, please close this issue.

**Comment by riadhnet** [comment]
not working in newer versions
