### ISSUE TITLE
Google Play services 9.0

### ISSUE THREAD

**Issue by ofirmiron** [mrmans0n/smart-location-lib#140]
Incompatible with Google Play services 9.0

**Comment by gogui63** [comment]
I'have this issue too, can you update to Google Play service 9.0 ?

**Comment by kristijandraca** [comment]
+1

**Comment by ofirmiron** [comment]
I just created a pull request to fix this issue.

**Comment by markmooibroek** [comment]
Impatiently waiting for the pull request to be merged ;-)

**Comment by mrmans0n** [comment]
As soon as it's green, guys

**Comment by ofirmiron** [comment]
Done! I will update it to 9.0.1 in a few days.

**Comment by markmooibroek** [comment]
Nice one =D

**Comment by mrmans0n** [comment]
Just uploaded the new artifact to maven central. Will be ready in one or two hours.
