### ISSUE TITLE
Not able to fetch the location

### ISSUE THREAD

**Issue by ShivamDev31** [mrmans0n/smart-location-lib#158]
Hi,

Thanks for the great lib. I'm facing an issue. I'm not able to fetch the user location.
Code : https://gist.github.com/ShivamDev31/891737d11258931be01463322cdfb133

Using the lib for rx maps : https://github.com/sdoward/RxGoogleMaps

Trying to make it work since hours but it didn't work out.

Also can I get the snippet to show the dialog to enable the location in case the location is disabled.
Also do you gave auto complete feature in the lib?

Hope to receive a response from you soon.

**Comment by mrmans0n** [comment]
Try in an actual device, with location in the manifest, and fused location provider. This works, the library is nothing more than a wrapper on what android location sends back to you. It can't be the one responsible for this not working for you.

**Comment by ShivamDev31** [comment]
Hi, I was trying in real device only. Worked after updating the lib. I think there was some play services version conflicts.

Can you tell me is there a way to show system dialog to enable location if the location is not enabled. As adding that involves a lot of bloatware so just wants to know if the library supports that, if yest then any snippet please?

**Comment by mrmans0n** [comment]
Not in the library, at this time. You'd have to roll out your own solution for this I'm afraid.
