### ISSUE TITLE
Cannot resolve v3.2.7

### ISSUE THREAD

**Issue by gouy-elliot** [mrmans0n/smart-location-lib#160]
Hi,

I got this error from Android Studio when I upgraded the new version:

`Error: Failed to resolve: io.nlopez.smartlocation:library:3.2.7`

Am I the only one ?

Best, Elliot

**Comment by ShivamDev31** [comment]
I think its still has not been updated in maven central. Till that time you can use 3.2.6 with play services 9.2.1

**Comment by mrmans0n** [comment]
done
