### ISSUE TITLE
RxJava 1 vs 2

### ISSUE THREAD

**Issue by KennyGoers** [mrmans0n/smart-location-lib#195]
Could you support or at least call out you are RxJava 2? Cost me much confusion as to why things that should be compatible were not.

**Comment by mrmans0n** [comment]
In the README for v 3.3.1 it says "The wrappers to rxjava2 are located in this package", so it's in there. I'll make it more prominent in the future, to avoid confusion.

If you want rxjava 1 support, you could use the v3.2.11 of the library. It doesn't need the extra dependency, only the :library one is enough.

**Comment by KennyGoers** [comment]
Thanks for the clarification, maybe an RxJava 1 vs 2 section that calls out the library for us that are stuck on 1 for a while. I read right over the rxjava2 reference you mentioned, thats on me.

**Comment by mrmans0n** [comment]
Yeah, maybe it'll be a good idea to create a new dependency to add rxjava1 support. Thanks for the idea :D
