### ISSUE TITLE
On location updated never called

### ISSUE THREAD

**Issue by rkumawat** [mrmans0n/smart-location-lib#20]
new SmartLocation.OnLocationUpdatedListener() {
        @Override
        public void onLocationUpdated(Location location, DetectedActivity detectedActivity) {
            // In here you have the location and the activity. Do whatever you want with them!
        }
    });

The code doesn't enter the following method hence returning the location null always. Any fixes?

**Comment by mona-baharlou** [comment]
I have this problem too. Does it solve @iphoneandroidtesting ? 
Every thing is OK , but In some places the locationUpdateListener not triggers.
