### ISSUE TITLE
smartlocation not working anymore

### ISSUE THREAD

**Issue by cleawrence** [mrmans0n/smart-location-lib#253]
Hi, your lib ist not getting position anymore ?
smartlocation not working anymore

**Comment by anuragrofers** [comment]
I agree too.

**Comment by anuragrofers** [comment]
My live project stopped working.

**Comment by yunusemrecetin** [comment]
Can you send Logcat log or exception detail?

**Comment by anuragrofers** [comment]
My main concern here is, sometimes it works and sometimes it fails.

**Comment by anuragrofers** [comment]
And anyway there is no log generated for SmartLocation

**Comment by cleawrence** [comment]
this is my crashlytics

com.google.android.gms.common.GooglePlayServicesUtilLight.isGooglePlayServicesAvailable (Unknown Source)
--
  | com.google.android.gms.common.GooglePlayServicesUtil.isGooglePlayServicesAvailable (Unknown Source)
  | io.nlopez.smartlocation.location.providers.LocationGooglePlayServicesWithFallbackProvider.<init> (LocationGooglePlayServicesWithFallbackProvider.java:31)
  | io.nlopez.smartlocation.SmartLocation.location (SmartLocation.java:59)
  | com.appiwedia.apps.android.bokitfinder.fragments.RestaurantActivityFragment$2.onResponseHTTP (RestaurantActivityFragment.java:264)
  | com.appiwedia.apps.android.bokitfinder.fragments.RestaurantActivityFragment$2.onResponseHTTP (RestaurantActivityFragment.java:260)
  | com.appiwedia.apps.android.bokitfinder.network.JacksonJsonRequest.deliverResponse (JacksonJsonRequest.java:49)
  | com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run (ExecutorDelivery.java:99)
  | com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1410)
