### ISSUE TITLE
more than one library with package name 'com.google.android.gms'

### ISSUE THREAD

**Issue by matantsu** [mrmans0n/smart-location-lib#30]
adding the library to my project gives the error as above.

```
Error:Execution failed for task ':app:processDebugResources'.
> Error: more than one library with package name 'com.google.android.gms'
  You can temporarily disable this error with android.enforceUniquePackageName=false
  However, this is temporary and will be enforced in 1.0
```

**Comment by intign** [comment]
Exactly the same issue. 

I tried adding 
 compile('com.google.maps.android:android-maps-utils:0.3') {
        exclude group: 'com.google.android.gms'
    }
still, error persisted.

**Comment by matantsu** [comment]
i have done:
```
compile 'com.google.android.gms:play-services:6.5.87'
compile ('io.nlopez.smartlocation:library:3.0.2'){ exclude group: 'com.google.android.gms'}
```

works for me.

**Comment by AlvarezAriel** [comment]
I just confirmed { exclude group: 'com.google.android.gms'} does the trick. Thanks!

**Comment by jvartanian94** [comment]
I believe the correct way to not include Play Services from this library would be to use { transitive = false; }

**Comment by gdky005** [comment]
please see here: http://blog.csdn.net/gdky005/article/details/45889897 !

**Comment by karan101292** [comment]
where to add {exclude group: 'com.google.android.gms'}
