### ISSUE TITLE
Callback no location available

### ISSUE THREAD

**Issue by skimarxall** [mrmans0n/smart-location-lib#33]
I think it's really important to know if we could get the location or not. Thus would be good to have a callback for it. Also would be good to know if it was the provider problem, so you can switch to a different provider.

**Comment by mrmans0n** [comment]
I will take a good look at solutions later today. What I uploaded was a quick fix but it has the TODOs so I don't forget. 

It seems to be a GoogleApiClient problem anyway. If you can't really trust that something run in `onConnected` is connected, well... it's a mess.

**Comment by mrmans0n** [comment]
Is this happening in the emulator only? 

I have only been able to reproduce things like this in the emulator but never on a device.

**Comment by skimarxall** [comment]
Mm not sure if you understood me. I meant that If you could add some callback when the provider fails. This can happen. 

For example on the GoogleServicesProvider 
@Override
    public void onConnectionFailed(ConnectionResult connectionResult) {
        logger.d("onConnectionFailed");

    }

Here would be good to have a listener so we know is not available. And maybe switch automatically to an other provider.

**Comment by mrmans0n** [comment]
I've added a listener with all the play services related callbacks (the failed and the other ones) in the snapshot 3.0.3-SNAPSHOT version, in maven central snapshot repo. 

In a few days I will probably release the 3.0.3 version with that fix. In the meantime you could use the snapshot one.

**Comment by skimarxall** [comment]
Awesome! I will take a look at it
