### ISSUE TITLE
Google map v2

### ISSUE THREAD

**Issue by crysan** [mrmans0n/smart-location-lib#34]
Can give an example with Google map v2?
Ty!

**Comment by mrmans0n** [comment]
What do you mean with this?

**Comment by crysan** [comment]
Example of connection of your library and check it on the performance when using Google Map.

**Comment by consp1racy** [comment]
@crysan Why should @mrmans0n come up with code for you?

I suggest closing this issue as unrelated.

**Comment by crysan** [comment]
Everything has already been decided. Thank U!
