### ISSUE TITLE
Google play services and other 

### ISSUE THREAD

**Issue by croccio** [mrmans0n/smart-location-lib#35]
Hi! How can i see with this library if google play services are installed? Or if cannot found location?

**Comment by skimarxall** [comment]
It has been added and it's available in snapshots see this issue https://github.com/mrmans0n/smart-location-lib/issues/33

**Comment by croccio** [comment]
how have i to write in gradle to take last snapshot?

**Comment by mrmans0n** [comment]
No need now , just update to version 3.0.3

**Comment by croccio** [comment]
How can i use that callback??

SmartLocation.with(QuiApi.getInstance().getApplicationContext()).location().oneFix()
                .start(new OnLocationUpdatedListener() {
                    @Override
                    public void onLocationUpdated(Location location) {
                        findPromotion(null, 0, location.getLatitude(), location.getLongitude(), callback);
                    }
                });


here i haven't any other callback, 've updated library.

**Comment by croccio** [comment]
IMO callback can be implemented in start() method.
In OnLocationUpdatedListener() add new callback onPlayServicesNotInstalled, OnLocationServicesDisabled and OnGPSDisabled, so when we call that method we have more possibilities to handle situation. I've tried to add this new feature but when i open your project i get an error in gradle

    Error:(83, 0) No such property: sonatypeRepo for class: org.gradle.api.publication.maven.internal.ant.DefaultGroovyMavenDeployer

and MavenDeployment is red. If you tell me how can i resolve this error i can do a pull request.

Thank you.
