### ISSUE TITLE
callback no gps

### ISSUE THREAD

**Issue by croccio** [mrmans0n/smart-location-lib#37]
i've opened new issue because you don't answer me, maybe you hadn't seen my question in a closed issue.

How can i use that callback??

    SmartLocation.with(QuiApi.getInstance().getApplicationContext()).location().oneFix()
                    .start(new OnLocationUpdatedListener() {
                        @Override
                        public void onLocationUpdated(Location location) {
                            findPromotion(null, 0, location.getLatitude(), location.getLongitude(), callback);
                        }
                    });

here i haven't any other callback, 've updated library.

@mrmans0n 

IMO callback can be implemented in start() method.
In OnLocationUpdatedListener() add new callback onPlayServicesNotInstalled, OnLocationServicesDisabled and OnGPSDisabled, so when we call that method we have more possibilities to handle situation. I've tried to add this new feature but when i open your project i get an error in gradle

    Error:(83, 0) No such property: sonatypeRepo for class: org.gradle.api.publication.maven.internal.ant.DefaultGroovyMavenDeployer

and MavenDeployment is red. If you tell me how can i resolve this error i can do a pull request, because is very simple to do. I've a custom lib to do this and do that what i tell you, but i prefer use this because is more complete.

Thank you.

**Comment by mrmans0n** [comment]
You have to define it in the provider. The default provider is already instantiated for you, but you can override it with a new one with the listener in. You can see it here: https://github.com/mrmans0n/smart-location-lib/blob/master/library/src/main/java/io/nlopez/smartlocation/location/providers/LocationGooglePlayServicesProvider.java

For example, with your code:

```java
SmartLocation.with(QuiApi.getInstance().getApplicationContext()).location().oneFix()
                .provider(new LocationGooglePlayServicesProvider(yourCallbackHere))
                .start(new OnLocationUpdatedListener() {
                    @Override
                    public void onLocationUpdated(Location location) {
                        findPromotion(null, 0, location.getLatitude(), location.getLongitude(), callback);
                    }
                });
```

As for the second thing you ask: if you copy gradle.properties.example to gradle.properties you would be able to run this project in your Android Studio.

**Comment by croccio** [comment]
Thank you very much :)

**Comment by croccio** [comment]
Ciao mrmans0n/smart-location-lib ,
C'è un messaggio per te in IQ Elite da Antonio Scardigno.   
Clicca qui a.iqelite.com/j/4QgNHj/qca/?hg=XsK03bkDPY per leggere il tuo messaggio 


IQ Elite Team



---------------------------------------------------------------------------
Questo messaggio era destinato a reply@reply.github.com. Se non desideri continuare a ricevere tali messaggi da IQ Elite, clicca su questo link: a.iqelite.com/common/unsubscribe/?code=79a73a01&email=reply@reply.github.com.&hg=XsK03bkDPY IQ Elite è un servizio con sede: C/Gran de Gracia 15, 2a 1a, 08012 Barcellona, Spagna.
---------------------------------------------------------------------------

**Comment by myflashlab** [comment]
```provider``` is private and can't call it like ```...oneFix().provider(...``` 
Any suggestions?
