### ISSUE TITLE
Location update not working in emulator

### ISSUE THREAD

**Issue by skimarxall** [mrmans0n/smart-location-lib#38]
Could it be that is not working?

I'm using genymotion, and with the gp service provider it only updates the location if I open google maps, and with the normal location provider it never gets triggered.

**Comment by mrmans0n** [comment]
So using LocationManagerProvider is not working for you in Genymotion? 

The default one, with the Play Services hacks that one has to do in Genymotion, is kind of understandable - but Genymotion should work okay with the LocationManagerProvider one, once you set up the location in there. Have you tried running the sample app in there?

**Comment by skimarxall** [comment]
I will try it and let you know.

**Comment by ultraon** [comment]
I use this code for Genymotion:
```java
SmartLocation.with(context).location().provider(new LocationManagerProvider()).oneFix().start(innerListener);
```
and i don't get any call for innerListener.onLocationUpdated(Location location);
