### ISSUE TITLE
provider

### ISSUE THREAD

**Issue by croccio** [mrmans0n/smart-location-lib#39]
If location services are enabled or disabled custom provider fall always in onConnected() and onResult(Status status) with status success. so i can't handle location services disable situation. is there another way to do this or it is an error?

**Comment by croccio** [comment]
@mrmans0n please give me an example that works. thank you very much for your work

**Comment by mrmans0n** [comment]
There is a snapshot version in maven central for the 3.0.4 version with an automatic fallback version that would do that for you. If I have time this week I will get that deployed in maven central. In the meantime you could play with it by downloading this project and playing a bit with the sample.

**Comment by croccio** [comment]
cannot find it 
io.nlopez.smartlocation:library:3.0.4-SNAPSHOT

**Comment by ultraon** [comment]
Can't find following:
- io.nlopez.smartlocation:library:3.0.4
- io.nlopez.smartlocation:library:3.0.4-SNAPSHOT

**Comment by mrmans0n** [comment]
For being able to use snapshot versions, you have to add the snapshot repository to your gradle config.

This is a snippet of my typical config:
```groovy
repositories {
    mavenLocal()
    mavenCentral()
    jcenter()
    maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }
}
```
