### ISSUE TITLE
Location request sometimes doesn't ever return

### ISSUE THREAD

**Issue by martynhaigh** [mrmans0n/smart-location-lib#40]
I'm having an issue in that quite often the library just won't return a location.  There are no logs which I can provide and there seems to be no reason why I'm seeing this behaviour.  I've tested across multiple devices and maybe one in every 4 or 5 requests wil just never return.  

Any ideas?

Code below:

    private void getLocation() {
        lastRequestTime = System.currentTimeMillis();
        Log.d(LOGTAG, "LocationHelper - getLocation - START");

        SmartLocation.with(context)
                .location()
                .oneFix()
                .start(new OnLocationUpdatedListener() {
                    @Override
                    public void onLocationUpdated(Location location) {
                        if (location == null) {
                            Log.d(LOGTAG, "LocationHelper - onLocationUpdated - NO LOCATION!");
                            return;
                        }
                        Log.d(LOGTAG, "LocationHelper - onLocationUpdated - Time to get location: " + ((System.currentTimeMillis() - lastRequestTime)/1000));
                        handleLocationUpdate(location);
                    }
                });
    }

**Comment by mrmans0n** [comment]
You can enable logging in the library. You have an example on how to do it in the sample application. Maybe that helps with your problem?
