### ISSUE TITLE
NoClassDefFoundError io.nlopez.smartlocation.location.providers.LocationGooglePlayServicesProvider

### ISSUE THREAD

**Issue by jaydeepw** [mrmans0n/smart-location-lib#41]
I already have Play services as a dependency in my project. So I add
compile ('io.nlopez.smartlocation:library:3.0.3'){
    transitive = false
}

to my dependencies and when the application tries to use the library, it crashes with following error

java.lang.NoClassDefFoundError: io.nlopez.smartlocation.location.providers.LocationGooglePlayServicesProvider
            at io.nlopez.smartlocation.SmartLocation$LocationControl.<init>(SmartLocation.java:89)
            at io.nlopez.smartlocation.SmartLocation.location(SmartLocation.java:43)
            at <my.package.names>

**Comment by jaydeepw** [comment]
Is anybody looking into this?

**Comment by mrmans0n** [comment]
Are you already importing play services to your dependencies? And is it the 6.5.87 version?

This could happen because you are setting up the transitive = false and you are using an old play services version. Either way, this is happening because something is wrong in your configuration.

You could try and download this project code and run the sample project. If it works, well, the problem is in your end :smile:

**Comment by jaydeepw** [comment]
Alright. Yes, you are right, I am using an older version of GPlay services. That, however, is for legacy reasons. I will try updating it for a while and try testing if my app works.

Thanks anyway for this small-little tool.

**Comment by mrmans0n** [comment]
You could always not use the transitive = false part, and use the LocationManagerProvider instead of the default one when setting up the provider in SmartLocation. It should work that way, but it wouldn't be using the fused location provider from play services. Maybe it's worth a try.

**Comment by JobGetabu** [comment]
A good work around towards this error is first 
add latest play services for location
`implementation 'com.google.android.gms:play-services-location:15.0.1'`

Add this to your manifest file
```
<meta-data
            tools:replace="android:value"
            android:name="com.google.android.gms.version"
            android:value="@integer/google_play_services_version" />
```
