### ISSUE TITLE
Non-negative loitering delay needs to be set when transition types include GEOFENCE_TRANSITION_DWELLING.

### ISSUE THREAD

**Issue by johnamcruz** [mrmans0n/smart-location-lib#42]
I am trying to use the geofencing feature but i keep getting this error. how to set the loitering delay?

**Comment by mrmans0n** [comment]
I am adding this value to the params of the GeofenceModel so it can be set. It will be ready when the 3.0.4 version of the library is released.

**Comment by mrmans0n** [comment]
Version 3.0.4 has access to that value, so you should be able to use setLoiteringDelay to your GeofenceModel with a value that does not make things go :boom:

**Comment by johnamcruz** [comment]
thanks for the update.
