### ISSUE TITLE
onGeofenceTransition not firing

### ISSUE THREAD

**Issue by johnamcruz** [mrmans0n/smart-location-lib#43]
i keep getting the message "geofencing event" on my log but it doesn't actually call the onGeofenceTransition event.

Any reason on why onGeofenceTransition would not fire?

**Comment by johnamcruz** [comment]
I ended up adding this to the method onReceive on GeofencingGooglePlayServicesProvider.

int transitionType = intent.getIntExtra(TRANSITION_EXTRA_ID, -1);
                ArrayList<String> geofencingIds = intent.getStringArrayListExtra(GEOFENCES_EXTRA_ID);
                for (final String geofenceId : geofencingIds) {
                    listener.onGeofenceTransition(new Geofence() {
                        @Override
                        public String getRequestId() {
                            return geofenceId;
                        }
                    }, transitionType);
                }

**Comment by mrmans0n** [comment]
Yes, sorry, I just noticed I never completed that. Sorry for the inconvenience. I will add this for the next version asap, I think I will be able to tomorrow :)

**Comment by mrmans0n** [comment]
I've released version 3.0.5 of the library with this part fixed. It will be available in maven central in a few hours.

**Comment by johnamcruz** [comment]
Thanks. that worked great.
