### ISSUE TITLE
Gradle Issue

### ISSUE THREAD

**Issue by vptcr** [mrmans0n/smart-location-lib#44]
Despite adding the "transitive" clause in Gradle, I am still getting the below error. Kindly help.

```
or:(44, 13) Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute meta-data#com.google.android.gms.version@value value=(@integer/google_play_services_version) from AndroidManifest.xml:44:13
  	is also present at io.nlopez.smartlocation:library:3.0.5:28:13 value=(6587000)
  	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:42:9 to override


  	Error:(46, 13) Attribute meta-data#com.google.android.gms.version@value value=(@integer/google_play_services_version) from AndroidManifest.xml:46:13
```

**Comment by c0nnector** [comment]
Had the same issue, i solved it by adding the tools:replace
Like this

`<meta-data
            tools:replace="android:value"
            android:name="com.google.android.gms.version"
            android:value="@integer/google_play_services_version" />`

**Comment by mrmans0n** [comment]
I will update the readme file with this too. I thought the compiler message was a dead giveaway there, but I guess it's better to add it to this library documentation too.
