### ISSUE TITLE
Location updates only once, even with .continuous()

### ISSUE THREAD

**Issue by c0nnector** [mrmans0n/smart-location-lib#47]
Just like the title says, this is the code

`SmartLocation.with(this).location()
                .continuous()
                .start(new OnLocationUpdatedListener() {
                    @Override
                    public void onLocationUpdated(Location location) {
                        //something
                    }
                });`

I'll get the location only once and then it stops

**Comment by mrmans0n** [comment]
I have this in production in a couple of projects and it is working. It's noteven needed to put .continuous(), as it should be the setting by default. 

If it keeps on happening, could you ellaborate more about where are you using this and what are you trying to do with it? That way I might pinpoint what's happening :)

**Comment by ronakmob** [comment]
@mrmans0n  Thank you so much for your quick response.

I would like to fetch location of every single minute , I think I found a solution by modifying LocationParams.

Thanks.

**Comment by tomsiwik** [comment]
Was wandering+walking myself without an update until i simply tried with a super high accuracy and interval. `LayoutParams.HIGH` triggers after some time too, simply not that often still battery saving.

Try out with the following exemplary settings and you'll see:

```Java
/**
 * Constants
 */
private static final LocationAccuracy ACCURACY_HIGH = LocationAccuracy.HIGH;    //HIGH
private static final long INTERVAL_HIGH = 1*1000;                               //1s
private static final float DISTANCE_HIGH = 1f;                                  //1m

/**
 * Location Parameters
 */
LocationParams locationParams = new LocationParams.Builder()
    .setAccuracy(ACCURACY_HIGH)
    .setInterval(INTERVAL_HIGH)
    .setDistance(DISTANCE_HIGH).build();

/**
 * SmartLocation Client
 */
smartLocation.location().config(locationParams).provider(...)
                .start(this);
```

Big thanks for this awesome library, btw.

**Comment by ronakmob** [comment]
@tomsiwik Awesome. Thanks for the response.
