### ISSUE TITLE
No interval

### ISSUE THREAD

**Issue by ronakmob** [mrmans0n/smart-location-lib#48]
This is awesome library and works fine. 
Doubt : Is there any way to set LocationUpdate interval ? 
onLocationUpdated getting called frequently but I would like to call it on every minutes, Is there any way to achieve this ?

Thanks

**Comment by mrmans0n** [comment]
Yes, if you submit a custom LocationParams object you can pretty much change anything. You can check its code out https://github.com/mrmans0n/smart-location-lib/blob/master/library/src/main/java/io/nlopez/smartlocation/location/config/LocationParams.java and you can see what you can change there. The interval is one of those things.

Then you can add change the config with something like this:

```java
SmartLocation.with(context).location().config(yourNewLocationParms).start(yourCallback);
```
