### ISSUE TITLE
No location available callback

### ISSUE THREAD

**Issue by bakua** [mrmans0n/smart-location-lib#50]
Hello, 
would it be please possible to add callback when no location is available?
I know about https://github.com/mrmans0n/smart-location-lib/issues/37 but solution there is only for when play services are not available. That solution does not handle when GPS is disabled by user on device.

Thank you :)

**Comment by mrmans0n** [comment]
I think I could do something about that. Thanks for the suggestion!

**Comment by mrmans0n** [comment]
I just submitted a new version of the library to maven central with some workaround for this. It's not a callback, but a state class called LocationState. You can access its methods like this:

```java
// This one returns a boolean stating wether or not the location services are enabled in system settings
SmartLocation.with(context).location().state().locationServicesEnabled()

// This one returns a boolean by checking if GPS or Network are available

// This one returns a boolean by checking if GPS is available
SmartLocation.with(context).location().state().isGpsAvailable()

// This one returns a boolean by checking if Network is available
SmartLocation.with(context).location().state().isNetworkAvailable()

// This one returns a boolean by checking if the passive provider is available (not very interesting)
SmartLocation.with(context).location().state().isPassiveAvailable()
```
