### ISSUE TITLE
LocationGooglePlayServicesProvider doesn't reconnect the GoogleApiClient on start()

### ISSUE THREAD

**Issue by lyssi** [mrmans0n/smart-location-lib#51]
Hi,

I seem to have encountered a problem with the LocationGooglePlayServicesProvider. After stop() has been called, a new start() never actually starts to retrieve a new location.

The reason for this is that stop() disconnects the GoogleApiClient. In start(), when the client is disconnected, only the shouldStart flag is set, probably assuming the the connection-call from init() is still running. However, connect() is never called again, and thus the onConnected()-callback, which would start the location update, is never called either.

Is this intentional? Otherwise it would be great if you could provide a fix.

**Comment by mrmans0n** [comment]
Good catch. I will be submitting a new version in a few hours with this fixed.

**Comment by lyssi** [comment]
Wow, that was super fast! Seems to work great now, thank you very much :+1:!

**Comment by mrmans0n** [comment]
Appreciated :smile:
