### ISSUE TITLE
Add a new method to provide a "trying"

### ISSUE THREAD

**Issue by ppamorim** [mrmans0n/smart-location-lib#55]
Will be good to add a method to provide a trying on oneFix() method.
Look like:

    int maxTimeRequest = 5000;

    SmartLocation.with(this)
          .location()
          .oneFix(5, maxTimeRequest) //Will try to get location 5 times in miliseconds.
          .statusCallback(new OnStatusCallbackListener(){}
          .start(new OnLocationUpdatedListener(){});

**Comment by adfleshner** [comment]
I second that motion this would be awesome. If not is there a way to set a timeout so it doesn't just sit there ( I have had times where I have waited 15 mins before.

**Comment by scottyab** [comment]
+1 for a time on oneFix

**Comment by mrmans0n** [comment]
I've answered a workaround in #68. I will close this thread and keep the discussion going in the other one.
