### ISSUE TITLE
Downloadable jar file needed

### ISSUE THREAD

**Issue by nologinatgit** [mrmans0n/smart-location-lib#58]
I've downloaded the source and try to run gradlew, but after 7 different errors, I can't compile the libary. Please, provice a usable **jar file** instead of the non-working gradle...

**Comment by mrmans0n** [comment]
https://travis-ci.org/mrmans0n/smart-location-lib/builds The build is passing in Travis, which means that the build.gradle file works perfectly (and not only locally). Do you have all the necessary dependencies downloaded? Did you copy the gradle.properties.example to gradle.properties (as the error might have suggested)?

Also, if you go to the Maven central search you got the binaries for the library. http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22io.nlopez.smartlocation%22%20AND%20a%3A%22library%22
