### ISSUE TITLE
Location updates callback never runs

### ISSUE THREAD

**Issue by nologinatgit** [mrmans0n/smart-location-lib#59]
I have added the project and Google Play Services, and inserted this line in the onCreate method:

        SmartLocation.with(context).location()
                .start(new OnLocationUpdatedListener() {
                    @Override
                    public void onLocationUpdated(Location location) {                       
                        Toast.makeText(context,"Lat: "+location.getLatitude(),Toast.LENGTH_LONG).show();
                    }
                });

When I debugged, the start call is made but the callback was never called.

What else should I set?

**Comment by mrmans0n** [comment]
Nothing else is needed, it would work like that. You get a callback invocation whenever the fused location provider detects a new fix. Are you testing this in a real device or an emulated one?

You could download an app like Fake GPS to mock some locations if you need that.

**Comment by nologinatgit** [comment]
It is a real device, but a rather old one (Android 2.3.6). I don't see any GPS activity (no GPS icon), so I don't know if it tries to acquire any location. Can I turn on any log to observe what the library does?

**Comment by mrmans0n** [comment]
Yup, just instantiate SmartLocation before using the .with(context) thing. There is a toggle in the class for setting up the logging.
