### ISSUE TITLE
geofence doesnt trigger

### ISSUE THREAD

**Issue by mynavy** [mrmans0n/smart-location-lib#60]
Amazing lib!
I made some intent service that implements location listener , activity listener and geo fencing listener all works but geo fencing listener doesnt trigger . 

is this issue known to happen ? or is it some bug ? 

Thanks.

**Comment by mynavy** [comment]
after a few resets of my phone + reset the app i got trigger but still it looks like it's not stable and im not sure why :/

**Comment by mrmans0n** [comment]
You have to play around with the distances a bit, as the geofencing is a bit flakey. This is not a library issue, it's more of a play services issue. For me it has worked nice with around 150m of radius.

**Comment by mynavy** [comment]
Thanks for the answer... 
Yeah you are right , google play services has some bugs ( like i said when i reboot the phone suddenly it's working) . 

another little question : 
Im also listening to location updates with the default settings. right now i can see that i got location 15 minutes ago and im not moving . how frequently i should see location updates with the default settings?

Thanks.

**Comment by mynavy** [comment]
strange looks like the location updates are not received at all with the default settings ( BEST_EFFORT).

im testing it already for 30 minutes and still no update.

**Comment by ppamorim** [comment]
Google geolocation sucks

**Comment by mynavy** [comment]
**Update**

After testing it for a day my conclusions are:

1. to listen for background activity recognition / location updates you need to create a Service and not an intent service that will listen.

2. geofencing does not work properly with that same service for some reason . I guess broadcast receiver would be a better thing for that.
