### ISSUE TITLE
Timeout for one fix.

### ISSUE THREAD

**Issue by adfleshner** [mrmans0n/smart-location-lib#68]
Is there timeout for 

 SmartLocation.with(getActivity()).location()
                    .oneFix()
                    .start(new OnLocationUpdatedListener() { 
                            @Override
                            public void onLocationUpdated(Location location) {

}}

Because I would like to have a one fix that happens every time I send something to a server. But I have waited over 2 1/2 hours hoping that something would kick off but as i write this the device is still stuck.

Im checking to make sure google services are installed as well as 
                SmartLocation.with(getActivity()).location().state().isAnyProviderAvailable() & 
                SmartLocation.with(getActivity()).location().state().locationServicesEnabled()
before I even attempt to get the location but it passes all of the checks and then just sits until I close the application. I would love a time out if that is possible.

**Comment by ppamorim** [comment]
The same of #55

**Comment by mrmans0n** [comment]
In the snapshot version (the betas for the next version I'm working on) I'm adding RxJava support. In RxJava there is a timeout strategy, and it would do exactly what you are asking. It's just a matter of wrapping the SmartLocation call like this (and then you modify the observable, like with the timeout stuff). 

```java
Observable<Location> location = ObservableFactory.from(SmartLocation.with(context).location().oneFix());
```

You have [the timeout documentation here](http://reactivex.io/documentation/operators/timeout.html).

As per support in the library itself, I will have to think about how to implement it correctly and if it's worth it. Just need to sit on it for a bit. If I needed this in one of my projects I would probably use the RxJava approach, so I recommend you that for the time being.

**Comment by mrmans0n** [comment]
RxJava enabled version 3.2.0 is now released. The Observables provide a timeout method which would do exactly what you guys want. 

I do not plan on adding native support for this for the time being. Maybe in the future, who knows, but now with RxJava support I think it would be enough :smile:

**Comment by riadhnet** [comment]
you are using old version of rxjava
  provided 'io.reactivex:rxjava:1.1.7'
   provided 'io.reactivex:rxandroid:1.2.0'
while this is the new one 
compile 'io.reactivex.rxjava2:rxandroid:2.0.1'
compile 'io.reactivex.rxjava2:rxjava:2.0.5'

couldn't use the new version since return object from  ObservableFactory is different

**Comment by timhuff** [comment]
@riadhnet Any workaround for this issue? I really need a timeout.

**Comment by riadhnet** [comment]
@timhuff 
my workaround 

```
  public static Observable<Location> from(final LocationControl locationControl) {
        Observable result = Observable.create(new ObservableOnSubscribe() {
            @Override
            public void subscribe(final ObservableEmitter e) throws Exception {
                locationControl.start(new OnLocationUpdatedListener() {
                    public void onLocationUpdated(Location location) {
                        e.onNext(location);
                    }
                });
            }
        }).doOnDispose(new Action() {
            @Override
            public void run() throws Exception {
                locationControl.stop();
            }
        });
        return result;
    }
```
then  

```
   Observable<Location> locationObservable = Utils.from(SmartLocation.with(this).location().oneFix().config(LocationParams.NAVIGATION));
        locationObservable.timeout(timeout, TimeUnit.SECONDS).take(1).subscribe(new Observer<Location>() {

            @Override
            public void onSubscribe(Disposable d) {
                showProgressDialog();
            }

            @Override
            public void onNext(Location location) {
                hideProgressDialog();
                onLocationListener.onLocation(location);
            }

            @Override
            public void onError(Throwable e) {
                hideProgressDialog();
                locationNotFoundSnack();

            }

            @Override
            public void onComplete() {
                hideProgressDialog();
            }
        });
```

**Comment by mrmans0n** [comment]
3.2.12-SNAPSHOT should have rxjava2 support, and 10.2.0 play services as well. I will probably work on decoupling the library from the rxjava dependency and add the support for that as a new dependency, so it is easier for everybody to update.

**Comment by huuhuybn** [comment]
you can make a class that call "TimeCounter" to check timeout. easy? Right . lol
Timer  timer = new Timer();
TimeCounter timeCounter = new TimeCounter(this, new OnGetGPS() {
                        @Override
                        public void onGetGPSFail() {
                            hideBusy();
                            showToast(getString(R.string.gps_not_available_toast));
                        }
                    });
                    timeCounter.runTimeCounter();
- Cancel timeCounter in your SmartLocation 
 SmartLocation.with(this).location().oneFix().start(new OnLocationUpdatedListener() {
                        @Override
                        public void onLocationUpdated(Location location) {
                            timeCounter.cancelTimeCounter();
                            hideBusy();
                        }
                    });
