### ISSUE TITLE
question about geocoding OnReverseGeocodingListener

### ISSUE THREAD

**Issue by ckdalsdhdp** [mrmans0n/smart-location-lib#70]
Hello I use smart-location-lib for reverse geocoding
When the second call of reverse method, onAddressResolved method call twice with past location data
I want reverse one time call with recently location data
thanks for reading please help me

**Comment by n1n3b1t** [comment]
I have the same issue - as far as I can see from code location or name is added to hashmap - but not cleared when response recieved. Please fix it(

**Comment by mrmans0n** [comment]
Will do when I am back from holidays, unless someone gives it a try and
send a PR with the fix 😅

**Comment by n1n3b1t** [comment]
if I'll have time I'll try to fix it tomorrow and send you a PR, if you can push it to gradle it would be awesome=)

**Comment by mrmans0n** [comment]
The fix will be live in the 3.2.0 version of the library. Thanks for pointing it out!
