### ISSUE TITLE
Run in background

### ISSUE THREAD

**Issue by mbmc** [mrmans0n/smart-location-lib#71]
Hi,

- if I use your library in an activity that continuously gets location updates, is it gonna get killed by the OS if it's put in the background for an extended time (~30min)
- is there any option to set an update frequency (like every 10s)

thanks

**Comment by mbmc** [comment]
for 2), found `LocationParams`

**Comment by mrmans0n** [comment]
About 1), it depends on the system and where you put your updates. I use this library currently in a Speed Camera detection app, and it doesn't get killed as long as I have it running on a Service. But you have to be careful with the battery drain.
