### ISSUE TITLE
Mock location

### ISSUE THREAD

**Issue by alorma** [mrmans0n/smart-location-lib#72]
Hi.

I'm trying to use this library, with default provider (google?), and mocking location in same time, because i need to test how app react when i'm moving.

So, is there any way to autodetect that we are mocking location? And if yes, how can i get that?

If not, i propouse to add it to the library, and when mocklocation is enabled, automaticically use this one as defaultm and if not results then default...

**Comment by alorma** [comment]
There's a method to check if mock location is enabled:

```java
public static boolean isMockSettingsON(Context context) {
  // returns true if mock location enabled, false if not enabled.
  if (Settings.Secure.getString(context.getContentResolver(),
                                Settings.Secure.ALLOW_MOCK_LOCATION).equals("0"))
     return false;
  else
     return true;
 }
```

**Comment by mrmans0n** [comment]
This will be available as part of the LocationState object in the upcoming 3.2.0 version. Thanks for the suggestion!
