### ISSUE TITLE
Missing an extra mode for GooglePlayServices provider

### ISSUE THREAD

**Issue by soymonitus** [mrmans0n/smart-location-lib#74]
switch (params.getAccuracy()) {
            case HIGH:
                request.setPriority(LocationRequest.PRIORITY_HIGH_ACCURACY);
                break;
            case MEDIUM:
                request.setPriority(LocationRequest.PRIORITY_BALANCED_POWER_ACCURACY);
                break;
            case LOW:
                request.setPriority(LocationRequest.PRIORITY_LOW_POWER);
                break;
        }

I miss the possibility to have an extra value: LOWEST, that will map to LocationRequest.PRIORITY_NO_POWER

**Comment by mrmans0n** [comment]
This mode will be there in the 3.2.0 version.

For backwards compatibility, in the LocationManager provider LOW will be the same as LOWEST.
