### ISSUE TITLE
Attribute meta-data$com.google.android.gms.version common issue unresolved on this situation

### ISSUE THREAD

**Issue by JCNeves** [mrmans0n/smart-location-lib#76]
After I updated your api, I got this problem:

![image](https://cloud.githubusercontent.com/assets/8627854/9176824/72136b2c-3f85-11e5-91f6-9e6731459b38.png)

I went to your common issues section:

![bug1](https://cloud.githubusercontent.com/assets/8627854/9176797/515e7fca-3f85-11e5-807c-4ecf0366eedc.PNG)

But your solution doesn't apply in my case because the meta-data you ask me to edit is generated on build:
![bug2](https://cloud.githubusercontent.com/assets/8627854/9176798/517a6d52-3f85-11e5-8bc6-7619927807f4.PNG)

How can i resolve this problem? Please help

**Comment by mrmans0n** [comment]
You have to edit your own manifest, the one for your app, with what's suggested in the error message, the tools:replace thing. That will fix it.
