### ISSUE TITLE
How to periodically ask location update?

### ISSUE THREAD

**Issue by ariefbayu** [mrmans0n/smart-location-lib#77]
Hi,

I am aware that `start()` will send location update periodically. However, I see the log that is spamming updates too fast (almost several times/second):

    08-19 09:35:26.473    8294-8294/? D/LOG﹕ Received Location Update: Location[fused -7.966620,112.632632 acc=4 et=+3h31m0s230ms alt=460.963806 vel=0.0]
    08-19 09:35:27.477    8294-8294/? D/LOG﹕ Received Location Update: Location[fused -7.966620,112.632632 acc=4 et=+3h31m1s231ms alt=460.963806 vel=0.0]
    08-19 09:35:28.477    8294-8294/? D/LOG﹕ Received Location Update: Location[fused -7.966620,112.632632 acc=4 et=+3h31m2s232ms alt=460.963806 vel=0.0]
    08-19 09:35:29.477    8294-8294/? D/LOG﹕ Received Location Update: Location[fused -7.966620,112.632632 acc=4 et=+3h31m3s232ms alt=460.963806 vel=0.0]
    08-19 09:35:30.477    8294-8294/? D/LOG﹕ Received Location Update: Location[fused -7.966620,112.632632 acc=4 et=+3h31m4s232ms alt=460.963806 vel=0.0]
    08-19 09:35:31.477    8294-8294/? D/LOG﹕ Received Location Update: Location[fused -7.966620,112.632632 acc=4 et=+3h31m5s233ms alt=460.963806 vel=0.0]
    08-19 09:35:32.477    8294-8294/? D/LOG﹕ Received Location Update: Location[fused -7.966620,112.632632 acc=4 et=+3h31m6s234ms alt=460.963806 vel=0.0]

How can I use this lib to only get update every 5 minutes or something like that?

**Comment by mrmans0n** [comment]
You have to pass your own [LocationParams](https://github.com/mrmans0n/smart-location-lib/blob/master/library/src/main/java/io/nlopez/smartlocation/location/config/LocationParams.java) into the SmartLocation call, with a `.config(params)` method invocation. That way you can define your own preferred accuracy, ms interval between reports, and even distance to move for your app to be notified.
