### ISSUE TITLE
Fix frequency for BEST_EFFORT strategy.

### ISSUE THREAD

**Issue by aandis** [mrmans0n/smart-location-lib#78]
What is the frequency of updates when using `BEST_EFFORT`? I am using this in a service and I get the update once when location is enabled on device but don't get any updates after that. Browsing the relevant [code](https://github.com/mrmans0n/smart-location-lib/blob/a899f3504e7f375975aabf348bc5809195a44b41/library/src/main/java/io/nlopez/smartlocation/location/config/LocationParams.java#L9) the distance is set to `150` and interval to `2500`. Does that mean the update frequency is every 150 meters and 2.5 seconds? 

PS - I'm aware of #47, but the workaround would be very power intensive.

**Comment by mrmans0n** [comment]
Those are arbitrary values. If you need something more specific you can do your own config params and use them with `.config(locationparams)`.
