### ISSUE TITLE
LocationState checking issue

### ISSUE THREAD

**Issue by davidbilly** [mrmans0n/smart-location-lib#82]
Hi @mrmans0n 

Thanks for this great lib :+1: 

I faced following issue with my HTC One m7, OS 4.2.2  with version io.nlopez.smartlocation:library:3.0.11 :

Scenario 1 :  if disable "Google location services" at setting, with GPS and 4G enabled
SmartLocation.with(context).location().state().locationServicesEnabled(); true
SmartLocation.with(context).location().state().isAnyProviderAvailable(); true 
SmartLocation.with(context).location().state().isGpsAvailable(); true
SmartLocation.with(context).location().state().isNetworkAvailable(); false 
SmartLocation.with(context).location().state().isPassiveAvailable(); true

Scenario 2 :  if disable "Google location services" at setting and disable GPS, with 4G enabled
SmartLocation.with(context).location().state().locationServicesEnabled(); false
SmartLocation.with(context).location().state().isAnyProviderAvailable(); true 
SmartLocation.with(context).location().state().isGpsAvailable(); true
SmartLocation.with(context).location().state().isNetworkAvailable(); false 
SmartLocation.with(context).location().state().isPassiveAvailable(); true

Scenario 3 :  if disable "Google location services",  disable GPS and 4G disable at setting
SmartLocation.with(context).location().state().locationServicesEnabled(); false
SmartLocation.with(context).location().state().isAnyProviderAvailable(); true 
SmartLocation.with(context).location().state().isGpsAvailable(); true
SmartLocation.with(context).location().state().isNetworkAvailable(); false 
SmartLocation.with(context).location().state().isPassiveAvailable(); true

Provider using "LocationGooglePlayServicesWithFallbackProvider" 
Logcat : Currently selected provider = LocationGooglePlayServicesProvider >> should be using "LocationManagerProvider" if on scenario 1

Something wrong on this state checker, any idea on this? Thanks!

**Comment by mrmans0n** [comment]
LocationState doesn't take into account the provider selected, just checks if the things are present at all.
