### ISSUE TITLE
onLocationUpdate() doesn't always fire

### ISSUE THREAD

**Issue by janswist** [mrmans0n/smart-location-lib#96]
I have this in my code and it seems to be working (the Navigation icon in status bar apppears), but even with `oneFix()` it remains on like it's waiting for something. Though, onLocationUpdated never triggers which is strange 'cause it worked before. I read other issues here and yes, I'm sitting under the roof, but still previously it returned coordinates properly - `getLastLocation()` is to little because I don't know when the last update was.

Logs says: 
`Currently selected provider = LocationGooglePlayServicesProvider`
`still not connected - scheduled start when connection is ok`

Code:
`SmartLocation.with(this).location().config(LocationParams.NAVIGATION)
                .oneFix()
                .start(new OnLocationUpdatedListener() {
                    @Override
                    public void onLocationUpdated(Location location) {
                        lat = location.getLatitude();
                        lng = location.getLongitude();
                        Log.i("ASD-localoca", lat + "/" + lng);
                    }
                });`

**Comment by mrmans0n** [comment]
Well, you said it yourself: you are under the roof. That + GPS flakiness explains this. The library is just a glorified wrapper around play services / location manager. We do pass through all that the core android location callbacks send.
